[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "flowcontrol"
version = "1.0.0"
description = "Toolbox for flow control problems"
authors = [{ name = "William Jussiau" }]
dependencies = [
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
