function [M] = read_coo(file)
% Read sparse matrix in COO format
fileload = load(file);
M = sparse(fileload.row+1,...
    fileload.col+1,...
    fileload.data,...
    fileload.shape(1), fileload.shape(2));
end