name: MPI Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
      - run: conda run -n fenics conda-develop src
      - run: conda run -n fenics mpirun -n 4 pytest tests/ -m mpi -q
