name: Fast Tests
on: [push, pull_request]
jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: "fenics"
          auto-activate-base: false
      - run: conda-develop src
      - run: pytest tests/ -m "not slow and not mpi" -q
